import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Front End</a>
        </h1>

        <p className={styles.description}>
          Belajar SYNRGY asyik dan menyenangkan
        </p>

        <div className={styles.grid}>
          <a href="/" className={styles.card}>
            <h2>Lingkungan Produktif</h2>
            <p>Suasana asyik dan produktif membuat belajar tidak akan bosan</p>
          </a>

          <a href="/" className={styles.card}>
            <h2>Peserta berbagai latar</h2>
            <p>Di sini peserta SYNRGY berbagai latar sosial, pendidikan, pekerjaan yang berpadu menambah networking</p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>Modul Lengkap dan relevan</h2>
            <p>Pengajaran mantap dan keren serta insightful dari Mentor</p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>Pencari jodoh</h2>
            <p>
              Pokoknya kamu betah belajar deh hehehehe
            </p>
          </a>
        </div>
        <div style={{textAlign:"center",marginBottom:"10px",marginTop:"5px"}}>
          <h3>Jangan sampai nyesel kalau belum daftar. Ayo daftar sekarang</h3>
          <button type="button" style={{backgroundColor:'blue',color:'white', padding:'8px 50px',borderRadius:'5px', border:'none'}} >Daftar</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
